### ISSUE TITLE
Blend: even for low values of top.A, bottom color appears mixed with top color

### ISSUE THREAD

**Issue by knieriem** [aykevl/ledsgo#1]
From my understanding the top color should have a minimal impact on the result for small values of top.A, or a zero impact if top.A == 0. Instead, in these cases top color values appear to be added to bottom color values.

Judging from my experiments with an LED strip, multiplying top color values with top.A seems to improve the result.

**Comment by aykevl** [comment]
Yeah, looking at that code it's very incorrect. There is also another blend function which is more correct, but still not entirely. I'll try to come up with a blend function that is fully correct but doesn't use division.

**Comment by aykevl** [comment]
Thanks, I've fixed this in https://github.com/aykevl/ledsgo/commit/5e99bdd55d580cc68f6d40b6d3734d9d67e97d9d.
